version: "3.7"

services:

  gigawall:
    image: "fizzbuzz2/python:gigawall"
    container_name: "gigawall"
    hostname: "gigawall"
    restart: always
    ports:
      - 8081:8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.gigawall.rule=Host(`gigawall.$MY_DOMAIN`)
      - traefik.http.routers.gigawall.entrypoints=websecure
      - traefik.http.routers.gigawall.tls.certresolver=myresolver
      - traefik.http.routers.gigawall.service=gigawall
      - traefik.http.services.gigawall.loadbalancer.server.port=8080


